In [1]:
#this notebook is building a new dataset to test why the zero class is not detected by branch exits

In [2]:
import pandas as pd
import numpy as np

# Make numpy values easier to read.
np.set_printoptions(precision=3, suppress=True)

import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.layers.experimental import preprocessing

In [3]:
dataset = tf.keras.datasets.cifar10.load_data()

In [4]:
(train_images, train_labels), (test_images, test_labels) = dataset

In [34]:

train_ds = tf.data.Dataset.from_tensor_slices((train_images, train_labels))
print(len(train_images))

50000


In [28]:
iterator = iter(train_ds)
iterator.get_next()

(<tf.Tensor: shape=(32, 32, 3), dtype=uint8, numpy=
 array([[[ 59,  62,  63],
         [ 43,  46,  45],
         [ 50,  48,  43],
         ...,
         [158, 132, 108],
         [152, 125, 102],
         [148, 124, 103]],
 
        [[ 16,  20,  20],
         [  0,   0,   0],
         [ 18,   8,   0],
         ...,
         [123,  88,  55],
         [119,  83,  50],
         [122,  87,  57]],
 
        [[ 25,  24,  21],
         [ 16,   7,   0],
         [ 49,  27,   8],
         ...,
         [118,  84,  50],
         [120,  84,  50],
         [109,  73,  42]],
 
        ...,
 
        [[208, 170,  96],
         [201, 153,  34],
         [198, 161,  26],
         ...,
         [160, 133,  70],
         [ 56,  31,   7],
         [ 53,  34,  20]],
 
        [[180, 139,  96],
         [173, 123,  42],
         [186, 144,  30],
         ...,
         [184, 148,  94],
         [ 97,  62,  34],
         [ 83,  53,  34]],
 
        [[177, 144, 116],
         [168, 129,  94],
         [179, 1

In [ ]:
features_ds = tf.data.Dataset.from_tensor_slices((train_images,train_labels_df))
iterator = iter(features_ds)
iterator.get_next()

In [5]:
# print(train_labels[:50])
unique, counts = np.unique(train_labels, return_counts=True)
dict(zip(unique, counts))

{0: 5000,
 1: 5000,
 2: 5000,
 3: 5000,
 4: 5000,
 5: 5000,
 6: 5000,
 7: 5000,
 8: 5000,
 9: 5000}

In [8]:
train_labels[train_labels == 0] = 255
# train_labels[train_labels == 6] = 254
# print(train_labels[:50])
unique, counts = np.unique(train_labels, return_counts=True)
dict(zip(unique, counts))



{1: 5000,
 2: 5000,
 3: 5000,
 4: 5000,
 5: 5000,
 6: 5000,
 7: 5000,
 8: 5000,
 9: 5000,
 255: 5000}

In [10]:
train_labels_df = pd.DataFrame(train_labels)
train_labels_df.to_csv("results/altTrain_labels2.csv", sep=',', mode='w',index=False,header=False)
unique, counts = np.unique(train_labels, return_counts=True)
dict(zip(unique, counts))

{1: 5000,
 2: 5000,
 3: 5000,
 4: 5000,
 5: 5000,
 6: 5000,
 7: 5000,
 8: 5000,
 9: 5000,
 255: 5000}

In [12]:
test_labels[test_labels == 0] = 255
unique, counts = np.unique(test_labels, return_counts=True)
dict(zip(unique, counts))

{1: 1000,
 2: 1000,
 3: 1000,
 4: 1000,
 5: 1000,
 6: 1000,
 7: 1000,
 8: 1000,
 9: 1000,
 255: 1000}

In [13]:
test_labels_df = pd.DataFrame(test_labels)
test_labels_df.to_csv("results/altTest_labels2.csv", sep=',', mode='w',index=False,header=False)

In [36]:
print(len(train_labels))

50000


In [32]:
features_ds = tf.data.Dataset.from_tensor_slices((train_images,train_labels_df))

In [33]:
iterator = iter(features_ds)
iterator.get_next()

(<tf.Tensor: shape=(32, 32, 3), dtype=uint8, numpy=
 array([[[ 59,  62,  63],
         [ 43,  46,  45],
         [ 50,  48,  43],
         ...,
         [158, 132, 108],
         [152, 125, 102],
         [148, 124, 103]],
 
        [[ 16,  20,  20],
         [  0,   0,   0],
         [ 18,   8,   0],
         ...,
         [123,  88,  55],
         [119,  83,  50],
         [122,  87,  57]],
 
        [[ 25,  24,  21],
         [ 16,   7,   0],
         [ 49,  27,   8],
         ...,
         [118,  84,  50],
         [120,  84,  50],
         [109,  73,  42]],
 
        ...,
 
        [[208, 170,  96],
         [201, 153,  34],
         [198, 161,  26],
         ...,
         [160, 133,  70],
         [ 56,  31,   7],
         [ 53,  34,  20]],
 
        [[180, 139,  96],
         [173, 123,  42],
         [186, 144,  30],
         ...,
         [184, 148,  94],
         [ 97,  62,  34],
         [ 83,  53,  34]],
 
        [[177, 144, 116],
         [168, 129,  94],
         [179, 1